/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bruce_demo_studydata_fragments_jnidemo_JNICalc */

#ifndef _Included_com_bruce_demo_studydata_fragments_jnidemo_JNICalc
#define _Included_com_bruce_demo_studydata_fragments_jnidemo_JNICalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bruce_demo_studydata_fragments_jnidemo_JNICalc
 * Method:    calc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bruce_demo_studydata_fragments_jnidemo_JNICalc_calc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
